services:
  - type: static
    name: trafuler-website
    rootDir: accueil/
    buildCommand: ""
    publishPath: .
    envVars:
      - key: NODE_VERSION
        value: 18.x
    headers:
      - path: /*
        name: Cache-Control
        value: no-cache
    